---
- hosts: localhost
  become: yes
  tasks:
  - name: install basic packages
    yum:  name=hwloc,hwloc-libs,numactl,numactl-libs

  - name: install mesos repository
    yum:  name=http://repos.mesosphere.com/el/7/noarch/RPMS/mesosphere-el-repo-7-1.noarch.rpm state=present

  - name: install mesos,zookeeper,marathon
    yum:  name=mesos,mesosphere-el-repo,mesosphere-zookeeper,marathon

  - name: start zookeeper in a single node
    service: name=zookeeper state=started

  - name: start mesos master
    service: name=mesos-master state=restarted

  - name: install mesos-agent isolation file
    copy: src=isolation
          dest=/etc/mesos-slave/isolation

  - name: install mesos-agent cgroups file
    copy: src=cgroups_enable_cfs
          dest=/etc/mesos-slave/cgroups_enable_cfs

  - name: install mesos-agent containerizers
    copy: src=containerizers
          dest=/etc/mesos-slave/containerizers

  - name: start mesos slave
    service: name=mesos-slave state=restarted

  - name: start marathon
    service: name=marathon state=restarted

